[mgr]
ratio = [1,3,5]
sort_by = "alphabetical"
sort_reverse = true
sort_dir_first = true
show_hidden = true
linemode = "size_and_mtime"

[preview]
max_width = 1000
max_height = 2000

[opener]
wps = [
  { run = """bash -c '
      set -e
      for f in "$@"; do
        d="$(dirname "$f")"
        b="$(basename "$f")"
        # 进到文件所在目录，用相对路径调用 wps（规避绝对路径 bug）
        ( cd "$d" && exec env XMODIFIERS="@im=fcitx" QT_IM_MODULE="fcitx5" /usr/bin/wps "./$b" ) &
      done
    ' _ $@""", desc = "WPS (debug foreground)", orphan = false, block  = true, for    = "unix" }
]

[open]
prepend_rules = [
  { name = "*.doc", use = "wps" },
  { name = "*.docx", use = "wps" },
  { name = "*.xls", use = "wps" },
  { name = "*.xlsx", use = "wps" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "wps" },
]
rules = [
    # 文本文件使用编辑器打开
    { mime = "text/*", use = ["edit", "reveal"] },
    # 图像文件直接打开
    { mime = "image/*", use = ["open", "reveal"] },
    # 媒体文件播放
    { mime = "{audio,video}/*", use = ["play", "reveal"] },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
